version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  # Backend API Service
  backend:
    build: ./backend
    container_name: inventory_backend
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/inventory_management"
      JWT_SECRET: "r8Kp2z9GQy7vH1sAqX4mN6bZ0cV8uY3tR5wQ2eFh9JkL0pS1"
      PORT: 5000
      CORS_ORIGIN: "http://localhost:5173"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - inventory_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "
      npm install &&
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db seed &&
      npm run dev
    "

  # Frontend Development Service (optional - can run separately)
  frontend:
    build: ./frontend
    container_name: inventory_frontend
    ports:
      - "5173:5173"
    networks:
      - inventory_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: "http://localhost:5000/api"
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge